[package]
name = "learn_rust"
version = "0.1.0"
authors = ["gordon <a731450465@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_redis = "0.3.44"
